title: RJ Novels
description: Light Novels & Web Novels PDF/EPUB

url: "https://rj-novels.github.io"
baseurl: "/RJ-Novels"

permalink: /:title/

markdown: kramdown

liquid:
  error_mode: warn

collections:
  novels:
    output: true
    permalink: /:name/
