title: RJ Novels
description: Download Light & Web Novel PDF/EPUB

url: "https://rj-novels.github.io"
baseurl: "/RJ-Novels"

permalink: /:title/

markdown: kramdown

liquid:
  error_mode: warn

collections:
  novels:
    output: true
    permalink: /:name/
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
    
feed:
  collections:
    novels:
      path: /novels.xml
      atom: true
